name: 'Issue Branch'
description: 'Creates branch based on issue.'
inputs:
  issue:
    description: 'Number of issue which title used to create branch name.'
    required: true
  base:
    description: 'Base branch to create new branch from.'
    default: master
    required: true
  create:
    description: 'Determines whether to create branch in repository.'
    default: true
    required: true
  comment:
    description: 'Determines whether to create comment in specified issue about branch creation.'
    default: false
    required: true
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'Owner and repository name. For example, "Codertocat/Hello-World".'
    default: ${{ github.repository }}
    required: true
  config:
    description: 'Path to file or config as value with generate settings. (Possible representation types: "Json" or "Yaml".)'
    default: |
      comment: |
        Create branch from `{base}`
        ```
        {branch}
        ```
    required: true
  context:
    description: 'Context can be specific value or file path, and can be accessed in text formatting context. (Possible representation types: "Json" or "Yaml".)'
    default: '{}'
    required: true
  output:
    description: 'Path to output result as file.'
    required: false
outputs:
  result:
    description: 'Action result.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'box'  
  color: 'gray-dark'
